### ISSUE TITLE
The cart content is coming wrong when recovering cart from email using PHP7

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/Woocommerce-abandon-cart-lite#109]
There are 2 products on the store. One worth 850 and another worth 1200. The cart was abandoned for 850 product with 2 qty for guest user.

The emails were sent with the correct cart content.

While recovering the cart by accessing the cart link in the email, the cart content is coming wrong. The cart had the product worth 1200. And the order was recovered too. The record from Abandoned Orders tab was moved to Recovered order with the product worth 1200. http://prntscr.com/cyaec3

![screenshot from 2016-10-24 18-33-16](https://cloud.githubusercontent.com/assets/7382505/19646713/64b0a4d8-9a18-11e6-99a2-62cc6b63eacb.png)

**Comment by Chetna1510** [comment]
I am not able to replicate the same issue on my local with PHP 7.

I have abandoned a cart with one product with the quantity 2 and the product price is 700.00. I have received the abandoned cart reminder email.
See the screenshot: http://screencast.com/t/UifLJw2iKR

While recovering the cart by accessing the cart link in the email, the cart content is not coming wrong. I have placed the order and for same cart, the order total is 1400 in the "Recovered Order" tab.

See this screenshot: http://screencast.com/t/LyMQdsQDV

**Comment by Chetna1510** [comment]
The issue was occurring due to wrong guest user's id. So, the cart content was coming of the registered user. To prevent this issue, we run a alter query to make that wrong id correct.

So, I am not able to replicate the issue with the github copy.

I had abandoned a cart as a guest user. Then I had accessed link from abandoned cart reminder email. My Cart content is correct.

Please see the screenshot: https://www.screencast.com/t/vCpDfKrP9

See this screenshot: https://www.screencast.com/t/Fp0Fehr7A
