### ISSUE TITLE
With the fresh install of the plugin, Multiple carts are created of the logged-in user.

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/Woocommerce-abandon-cart-lite#403]
I had installed and activated the github copy of the plugin on my local server, then visited site as an Admin and went to shop page and added the product to the cart. Screenshot: http://prntscr.com/lbr6w1

I had not visited cart page. Also, there was already two products were added to the cart. 

After that, I had abandoned a cart as a guest user. And then checked on Abandoned Orders tab after cut off time, multiple carts were created for the logged-in user with the same abandoned date. Screenshot: http://prntscr.com/lbr8da

The Id is also showing in the ascending order.

**Comment by apeksha10** [comment]
This same issue replicate with guest users
Take latest git copy on 30-10-2018
After update latest git copy, one visitor cart captured.
I am not added any of product
see the screenshot : https://www.screencast.com/t/4XWAeIMW06V

I think this issue replicate only one time when you update or install latest git copy 
But need to check what is exact root cause for this issue

**Comment by pinalj** [comment]
The issue seems to be replicated only when u abandon a cart within the first few minutes of installing the plugin. 

1. Added products as admin to the cart.
2. Deleted the existing plugin copy and ran a fresh install.
3. Set cut off to 3 mins
4. After 5 mins or so - added a product to the already existing cart as admin

The first record (created when we install the plugin) was marked as ignored and a new record was created.

**Comment by pinalj** [comment]
As far as I have been able to tell, on a fresh install one admin cart is being captured for the registered user that is logged in. In the latest copy I've not observed any visitor carts being captured. Hence closing the issue.
