### ISSUE TITLE
5.1.3: Fatal error: require_once(): Failed opening required 'component/woocommerce-check/ts-woo-active.php'

### ISSUE THREAD

**Issue by jokanane** [TycheSoftwares/Woocommerce-abandon-cart-lite#426]
There seems to be an issue with a file name / path in version 5.1.3 (updated today):

```
Warning: require_once(component/woocommerce-check/ts-woo-active.php): failed to open stream: No such file or directory in /home/.../plugins/woocommerce-abandoned-cart/includes/wcal_all_component.php on line 28

Fatal error: require_once(): Failed opening required 'component/woocommerce-check/ts-woo-active.php' (include_path='.:/usr/local/php72/lib/php') in /home/.../plugins/woocommerce-abandoned-cart/includes/wcal_all_component.php on line 28
```

```
$ ls /home/.../plugins/woocommerce-abandoned-cart/includes/component/WooCommerce-Check/
Instructions  ts-woo-active.php
```

Reverting the name of the required file (directory path) resolves the error.

**Comment by dhruvintyche** [comment]
@jokanane it's strange that you had to change the folder name in the file but we would like to debug the issue.

It would be helpful if you can share us some information related to the below questions:
* How did you update the plugin copy? Was it via the WordPress updater or Automatic updater or manually via FTP
* Is the WordPress installation where the error occured on a Windows local server or Linux based server? We are asking this since Windows system sometimes ignores the casing difference for Folders
* Are there any permissions set to the folders where plugin is installed?
* Was there any caching plugin installed that could have caused the issue to occur?

We did change the folder name to lower case here: https://prnt.sc/loy6z6 also at the places where it is referenced here: https://github.com/TycheSoftwares/Woocommerce-abandon-cart-lite/blob/master/woocommerce-abandoned-cart/includes/wcal_all_component.php#L28 

Also, none of the other lite users have reported anything related to this. We would be glad to have a look at the issue you faced.

Thanks!

**Comment by jokanane** [comment]
Hmm... Looks now that git (on OS X) has ignored the camelcase change.

Sorry, I should've checked more carefully.

Fixed now locally. You may close the issue.

**Comment by dhruvintyche** [comment]
no worries @jokanane .. closing this issue.
