### ISSUE TITLE
Add a filter to remove the price column from the reminder email.

### ISSUE THREAD

**Issue by priyanka-tychesoftwares** [TycheSoftwares/Woocommerce-abandon-cart-lite#618]
We should add a filter to remove the price column from the reminder email.

One of our clients wants to remove the price column from the reminder email as she is using the Woocommerce Price based on Country plugin for displaying the price in different currencies based on the customer's country. And our plugin is not compatible with it. So this client wants to display only the Product image and the Product name columns in the reminder email.

Ticket link: https://tychesoftwares.freshdesk.com/a/tickets/17131

**Comment by dhruvins** [comment]
@apeksha10 please refer the Wiki page while testing this issue where examples have been added on how to remove the columns from reminder emails

**Comment by pinalj** [comment]
The client wanted to hide the prices as they were displayed incorrectly due to a conflict with another plugin. So we provided some filters which can be used to hide certain columns in the reminder emails as below:

Quantity column
1. wcal_reminder_email_qty_header - this will change the value of the column name 'Quantity' 
2. wcal_reminder_email_qty_value - this will change the value of the column for each product in the Quantity column
when both are  returned blanks, the column will be hidden.

Similarly - Price Column
1. wcal_reminder_email_price_header - this will change the value of the column name 'Price'
2. wcal_reminder_email_price_value - this will change value of column for each product in the Price column
when both are  returned blanks, the column will be hidden.

Similarly:
1. wcal_reminder_email_line_subtotal_header - this will change the value of the column name 'Line Subtotal'
2. wcal_reminder_email_line_subtotal_value - this will change the value of the column for each product in the Line Subtotal column
when both are  returned blanks, the column will be hidden.

Similarly, totals:
1. wcal_reminder_email_cart_total_title - changes the value of the text 'Cart Total'
2. wcal_reminder_email_cart_total - changes the final cart amount 
when left blanks, the row will be hidden

It should be noted here that all the price amounts are wc_price() formatted.

**Comment by apeksha10** [comment]
I checked all filters together and all are working fine.
https://www.screencast.com/t/OuvpR1xuC
